### ISSUE TITLE
Reporte de Practica 5 Equipo Mana

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipomana#1]
[Reporte de Practica 5 Equipo Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipomana/files/12825822/Reporte.de.Practica.5.Equipo.Mana.pdf)

**Comment by Edwin14459** [comment]
_Calificación Final:_ **20/20**
**_Excelente Trabajo:_** La práctica cumple con la rúbrica, esta bien estructurada y los procedimientos que hicieron son muy entendibles.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
